// Code generated by voauto-gen; DO NOT EDIT.
package profile

import (
	"github.com/take0fit/validationcontext"
	"github.com/take0fit/validationcontext/voauto"
)

func init() {
	// Fully qualified key (unique across different packages)
	voauto.Register("user_valueobject_profile_NewFirstName",
		func(v any, vc *validationcontext.ValidationContext) any {
			return NewFirstName(v.(string), vc)
		})
	// Fully qualified key (unique across different packages)
	voauto.Register("user_valueobject_profile_NewLastName",
		func(v any, vc *validationcontext.ValidationContext) any {
			return NewLastName(v.(string), vc)
		})
}
