package generator

// registryTemplate is the Go template for generating registry files
const registryTemplate = `// Code generated by voauto-gen; DO NOT EDIT.
package {{.PackageName}}

import (
	"github.com/take0fit/validationcontext"
	"github.com/take0fit/validationcontext/voauto"
{{- range .Imports}}
	{{.Alias}} "{{.Path}}"
{{- end}}
)

func init() {
{{- range .Registrations}}
	// Fully qualified key (unique across different packages)
	voauto.Register("{{.RegistrationKey}}",
		func(v any, vc *validationcontext.ValidationContext) any {
			return {{.QualifiedName}}(v.({{.ParamType}}), vc)
		})
{{- end}}
}`
