name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.2

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Run tests and measure coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}' > coverage.txt

      - name: Check coverage
        run: |
          COVERAGE=$(cat coverage.txt)
          echo "Coverage: ${COVERAGE}%"
          if (( $(echo "${COVERAGE} < 60" | bc -l) )); then
            echo "Coverage is below 60%"
            exit 1
          fi
